### ISSUE TITLE
软件包页面错位

### ISSUE THREAD

**Issue by xiaozhuai** [jerrykuku/luci-theme-argon#408]
- Versiosn: OpenWrt 22.03.0
 - Theme argon
 - Version 2.3.1

![image](https://user-images.githubusercontent.com/4773701/234171945-827c117d-67b5-428e-9402-be687490e530.png)

看了一下，这里`vertical-align`应该为`super`
```css
label>input[type="checkbox"],
label>input[type="radio"] {
    position: relative;
    top: .4rem;
    right: .2rem;
    margin: 0;
    vertical-align: bottom;
}
```

修复后
![image](https://user-images.githubusercontent.com/4773701/234171996-bd165fe4-33bb-4120-b9de-59c7adf333c5.png)
