### ISSUE TITLE
lede下更新固件页面样式修改建议

### ISSUE THREAD

**Issue by yhl452493373** [jerrykuku/luci-theme-argon#426]
现在的样式
<img width="846" alt="image" src="https://github.com/jerrykuku/luci-theme-argon/assets/26134687/1437b6b4-7d35-49df-8895-b20ba1d0e617">

修改后如截图，我观察了下，选择器`.node-system-flashops fieldset > ul`只影响这个页面，具体内容：
```css
.node-system-flashops fieldset > ul {
    padding: 1rem;
}
```
<img width="1149" alt="image" src="https://github.com/jerrykuku/luci-theme-argon/assets/26134687/8af43c37-3b0c-49e2-9733-fdef3573210d">
