### ISSUE TITLE
Luci-app-diskman 应用 格式化窗口背景没有适配深色模式。

### ISSUE THREAD

**Issue by Zisbusy** [jerrykuku/luci-theme-argon#504]
**Describe the bug**
Luci-app-diskman 应用 格式化窗口背景没有适配深色模式。
Chrome 125.0.6422.142
OpenWrt v23.05.3
![WeChat8e25e3765b2be867a9e924d0ca3b4cd5](https://github.com/jerrykuku/luci-theme-argon/assets/49525016/e182464a-d301-4353-857f-bc1c38bebbdd)

**Comment by Zisbusy** [comment]
[data-page="admin-system-diskman-partition-sdb"] #dialog_format .dialog_box {
  background-color: #1e1e1e;
}

添加这个样式可以解决。

**Comment by sbwml** [comment]
牛逼。够细节的，这样都能发现。

不过从你截图来看，这个估计单靠主题无法改变它的样式，因为它是 CBI 页面，只能从 diskman luci 应用自身来做深色模式兼容

**Comment by sbwml** [comment]
大概这可以这样改

```css
  @media (prefers-color-scheme: dark) {
    #dialog_format .dialog_box {
      background: #222222 !important;
  }
```

https://github.com/sbwml/openwrt_pkgs/commit/ef5087960ca62152981150c4f1d00deb799ad5a8

![image](https://github.com/jerrykuku/luci-theme-argon/assets/16485166/00a33f61-6344-4fa5-9278-7440393e1c68)
![image](https://github.com/jerrykuku/luci-theme-argon/assets/16485166/1a8bbde8-3ef0-4b13-bbcc-b6c62744695f)
