### ISSUE TITLE
Wrong colors after login in dark mode

### ISSUE THREAD

**Issue by batorencjusz** [jerrykuku/luci-theme-argon#559]
Hello, 

After login, in dark mode colors are wrong, if i reload page nothing changes, if i click again into info panel then colors are ok.

![Image](https://github.com/user-attachments/assets/9c1ec6a4-807d-465e-9cfa-d3dd18ab5b38)

**Comment by jerrykuku** [comment]
Is infopanel a newly added interface? I remember there was no this page in the original openwrt.

**Comment by batorencjusz** [comment]
Its luci app dashboard, if i changed values mentioned above everything looks ok.

Could you tell me what bandwith monitor did you use on theme preview?

**Comment by wirl** [comment]
Can confirm that each time when you login the dashboard mod is not dark. Refreshing the page does not fix it but clicking the dashboard link on the left again does fix it. The mod has been available in OpenWrt for quite some time but not very widely used I think.

https://github.com/openwrt/luci/tree/master/modules/luci-mod-dashboard

**Comment by sbwml** [comment]
你可以使用自己喜欢的颜色去填充界面，类似这样（但肯定不是复制粘贴）：

```css
/* luci-mod-dashboard */
.Dashboard .dashboard-bg {
  background-color: #1b212a !important;
}

.Dashboard h3 {
  color: #cccccc !important;
  border-radius: 0 0 16px 16px;
}

.Dashboard:not(.some-other-class) {
  color: #cccccc !important;
}

.Dashboard .title {
  background-color: #444950 !important;
  border-radius: 16px;
}

.Dashboard .cbi-rowstyle-1 {
  background-color: #1b212a;
}
```

![Image](https://github.com/user-attachments/assets/123fccfa-c85b-47fa-b20f-ae02421b6136)
